let supabaseKey = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdXJneHN4cXZyZGZyeGticnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NjExODksImV4cCI6MjA3NjEzNzE4OX0.Xjny_CN8fp0hmqvvlQJCjevN2-7lhvIpXG4cL_xz8f8
let supabaseUrl = "https://npurgxsxqvrdfrxkbrri.supabase.co"
const supabase = supabasejs.createClient(supabaseUrl, supabaseKey)